name: teleop-utils
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cxx-compiler
  - cmake
  - boost
  - spdlog
  - pybind11
  - zeromq
  - cppzmq
  - flask
  - flask-socketio
  - transforms3d
  - qrcode
  - pygame
  - pynput
  - click
  - av
  - opencv
  - pyzbar
  - scipy
  - pip:
      - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz
